# Generated by Django 2.1.7 on 2019-09-06 14:54

import STTEAPI.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Alumno',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('contenido_subido', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Documento',
            },
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('columna_csv', models.IntegerField(blank=True, null=True)),
                ('nombre_mostrar', models.CharField(blank=True, max_length=100, null=True)),
                ('mostrar', models.IntegerField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Paso',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('columna_matricula', models.IntegerField(blank=True, null=True)),
                ('columna_ticket', models.IntegerField(blank=True, null=True)),
                ('columna_fecha_inicio', models.IntegerField(blank=True, null=True)),
                ('columna_fecha_ultima_actualizacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Proceso',
            },
        ),
        migrations.CreateModel(
            name='Tramitealumno',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_ticket', models.IntegerField(unique=True)),
                ('numero_paso_actual', models.IntegerField(unique=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('encuesta', models.IntegerField(default=0)),
            ],
            options={
                'managed': False,
                'db_table': 'TramiteAlumno',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField(default=False)),
                ('is_staff', models.IntegerField(default=False)),
                ('is_active', models.IntegerField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_admin', models.IntegerField(default=False)),
                ('es_alumno', models.IntegerField(default=False)),
            ],
            options={
                'managed': False,
                'db_table': 'Usuario',
            },
            managers=[
                ('objects', STTEAPI.models.MyUserManager()),
            ],
        ),
    ]
