# Generated by Django 2.1.11 on 2019-10-12 22:13

import STTEAPI.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Administrador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('siglas_carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('periodo_de_aceptacion', models.CharField(blank=True, max_length=100, null=True)),
                ('posible_graduacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_de_nacimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Alumno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('administrador', models.ForeignKey(db_column='administrador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='STTEAPI.Administrador')),
            ],
            options={
                'db_table': 'Carta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CartaAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_terminacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('administrador', models.ForeignKey(db_column='administrador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='STTEAPI.Administrador')),
                ('alumno', models.ForeignKey(db_column='alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='STTEAPI.Alumno')),
                ('carta', models.ForeignKey(db_column='carta', on_delete=django.db.models.deletion.DO_NOTHING, to='STTEAPI.Carta')),
            ],
            options={
                'db_table': 'CartaAlumno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('administrador', models.ForeignKey(db_column='administrador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='STTEAPI.Administrador')),
            ],
            options={
                'db_table': 'Documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('mostrar', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Paso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('num_pasos', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('administrador', models.ForeignKey(db_column='administrador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='STTEAPI.Administrador')),
            ],
            options={
                'db_table': 'Proceso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tramitealumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('numero_ticket', models.IntegerField(default=0, unique=True)),
                ('encuesta', models.IntegerField(default=0)),
                ('administrador', models.ForeignKey(db_column='administrador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='STTEAPI.Administrador')),
                ('alumno', models.ForeignKey(db_column='alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='STTEAPI.Alumno')),
                ('paso', models.ForeignKey(db_column='paso', on_delete=django.db.models.deletion.DO_NOTHING, to='STTEAPI.Paso')),
                ('proceso', models.ForeignKey(db_column='proceso', on_delete=django.db.models.deletion.DO_NOTHING, to='STTEAPI.Proceso')),
            ],
            options={
                'db_table': 'TramiteAlumno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_admin', models.BooleanField(default=False)),
                ('es_alumno', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': True,
            },
            managers=[
                ('objects', STTEAPI.models.MyUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='paso',
            name='proceso',
            field=models.ForeignKey(db_column='proceso', on_delete=django.db.models.deletion.DO_NOTHING, to='STTEAPI.Proceso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='usuario',
            field=models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrador',
            name='usuario',
            field=models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
