version: '2.4'

volumes:
  mysql_data: 

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 3x4mPl3P4sSW0rD!
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root

  backend:
    image: proyecto_integrador/stta:backend
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:8000
    volumes:
      - ./back-end:/usr/src
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /usr/src
    stdin_open: true
    tty: true
    depends_on:
      - mysql

  frontend:
    image: proyecto_integrador/stta:frontend
    build:
      context: .
      dockerfile: front.Dockerfile
      target: development
    ports:
      - 5000:3000
    volumes:
      - ./front-end:/usr/src
      - /usr/src/node_modules
    command: npm run start
    working_dir: /usr/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
