version: '3'

services:
  web:
    build: .
    env_file:
    - web-variables.env
    command: uwsgi --http :8000 --module STTEAPI.settings.wsgi
    volumes:
      - .:/stte-back
    ports:
      - "8000:8000"
